replicaCount: 1

image:
  repository: docker.io/map7000/prayingtimes-timeskeeper
  pullPolicy: Always
  tag: ""

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: 8080

javaOptions: "-Dspring.config.location=classpath:/application.yaml -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0"